"""Mini-tool endpoints — AI detection and plagiarism checking."""

import asyncio
import re

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ResultMessage,
    TextBlock,
    query,
)

from engine.agents.base import _get_api_key
from engine.logging_config import get_logger
from engine.tools.bright_data import BrightDataClient, ScrapedPage

logger = get_logger(__name__)

router = APIRouter(prefix="/api/tools", tags=["tools"])

# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    url: str
    mode: str = "text"  # "text" | "image" | "auto"


class DetectionResult(BaseModel):
    url: str
    verdict: str            # "ai_generated" | "human_written" | "mixed" | "inconclusive"
    confidence: float       # 0-1
    summary: str
    indicators: list[str]
    content_type: str       # "text" | "image"
    content_preview: str    # first ~300 chars of scraped content


class PlagiarismRequest(BaseModel):
    url: str


class PlagiarismMatch(BaseModel):
    passage: str
    source_url: str
    source_title: str
    similarity: str  # "high" | "moderate" | "low"


class PlagiarismResult(BaseModel):
    url: str
    originality_score: float  # 0-1 (1 = fully original)
    verdict: str              # "original" | "partially_plagiarized" | "heavily_plagiarized"
    summary: str
    matches: list[PlagiarismMatch]
    content_preview: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_env() -> dict[str, str]:
    """Build env dict with API key for Claude Agent SDK calls."""
    env: dict[str, str] = {}
    if api_key := _get_api_key():
        env["ANTHROPIC_API_KEY"] = api_key
    return env


async def _call_claude(prompt: str, model: str = "sonnet", max_tokens: int = 1024) -> str:
    """Call Claude via the Agent SDK (same auth as the research engine)."""
    env = _build_env()
    options = ClaudeAgentOptions(
        model=model,
        max_turns=1,
        allowed_tools=[],
        system_prompt="You are an analysis assistant. Follow instructions precisely and output in the exact format requested.",
        env=env,
    )

    response_text = ""

    async def _run():
        nonlocal response_text
        async for message in query(prompt=prompt, options=options):
            if isinstance(message, AssistantMessage):
                for block in message.content:
                    if isinstance(block, TextBlock):
                        response_text += block.text

    await asyncio.wait_for(_run(), timeout=120)
    return response_text


def _get_bright_data() -> BrightDataClient:
    return BrightDataClient()


async def _scrape_url(url: str) -> ScrapedPage:
    """Scrape a URL via Bright Data and return markdown content."""
    bd = _get_bright_data()
    try:
        page = await bd.scrape_page(url, fmt="markdown")
        if page.ok:
            return page
        return ScrapedPage(url=url, content="", ok=False, error=page.error or "Failed to scrape page")
    except Exception as e:
        logger.warning("Scrape failed for %s: %s", url, e)
        return ScrapedPage(url=url, content="", ok=False, error=str(e))


# ---------------------------------------------------------------------------
# AI Content Detection
# ---------------------------------------------------------------------------

@router.post("/detect-ai", response_model=DetectionResult)
async def detect_ai_content(req: AnalyzeRequest):
    """Detect whether content at a URL is AI-generated."""
    page = await _scrape_url(req.url)
    if not page.ok or not page.content.strip():
        raise HTTPException(status_code=422, detail=f"Could not scrape content from URL: {page.error or 'empty page'}")

    content = page.content[:12000]  # cap for context window
    preview = page.content[:300]

    prompt = f"""Analyze the following web content and determine whether it was written by a human or generated by AI (like ChatGPT, Claude, etc.).

URL: {req.url}

CONTENT:
{content}

Provide your analysis in EXACTLY this format (no markdown fences):
VERDICT: <ai_generated|human_written|mixed|inconclusive>
CONFIDENCE: <0.0 to 1.0>
SUMMARY: <2-3 sentence explanation>
INDICATORS:
- <indicator 1>
- <indicator 2>
- <indicator 3>
- <indicator 4>
- <indicator 5>

Focus on: repetitive sentence structures, lack of personal voice, hedging language ("It's important to note"), formulaic transitions, unusual uniformity in paragraph length, lack of specific personal experience, generic examples, and characteristic AI phrasings."""

    try:
        text = await _call_claude(prompt, model="sonnet")

        verdict = "inconclusive"
        confidence = 0.5
        summary = ""
        indicators: list[str] = []

        for line in text.split("\n"):
            line = line.strip()
            if line.startswith("VERDICT:"):
                v = line.split(":", 1)[1].strip().lower()
                if v in ("ai_generated", "human_written", "mixed", "inconclusive"):
                    verdict = v
            elif line.startswith("CONFIDENCE:"):
                try:
                    confidence = float(line.split(":", 1)[1].strip())
                    confidence = max(0.0, min(1.0, confidence))
                except ValueError:
                    pass
            elif line.startswith("SUMMARY:"):
                summary = line.split(":", 1)[1].strip()
            elif line.startswith("- "):
                indicators.append(line[2:].strip())

        return DetectionResult(
            url=req.url,
            verdict=verdict,
            confidence=confidence,
            summary=summary or "Analysis completed.",
            indicators=indicators[:8],
            content_type="text",
            content_preview=preview,
        )
    except Exception as e:
        logger.error("AI detection failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")


# ---------------------------------------------------------------------------
# Plagiarism Checking
# ---------------------------------------------------------------------------

@router.post("/check-plagiarism", response_model=PlagiarismResult)
async def check_plagiarism(req: PlagiarismRequest):
    """Check content at a URL for potential plagiarism."""
    page = await _scrape_url(req.url)
    if not page.ok or not page.content.strip():
        raise HTTPException(status_code=422, detail=f"Could not scrape content from URL: {page.error or 'empty page'}")

    content = page.content[:12000]
    preview = page.content[:300]

    # Step 1: Extract key passages for search
    extract_prompt = f"""Extract 5 distinctive passages (1-2 sentences each) from this content that would be most useful for plagiarism detection. Choose passages with specific claims, unique phrasing, or factual statements — not generic introductions.

CONTENT:
{content}

Return ONLY the passages, one per line, prefixed with PASSAGE: (no numbering, no quotes)."""

    try:
        extract_text = await _call_claude(extract_prompt, model="haiku")
        passages = []
        for line in extract_text.split("\n"):
            line = line.strip()
            if line.startswith("PASSAGE:"):
                p = line.split(":", 1)[1].strip().strip('"').strip("'")
                if len(p) > 20:
                    passages.append(p)
        passages = passages[:5]

        if not passages:
            # Fallback: split content into chunks
            sentences = re.split(r'(?<=[.!?])\s+', content)
            passages = [s for s in sentences if len(s) > 40][:5]

    except Exception as e:
        logger.error("Passage extraction failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")

    # Step 2: Search for each passage
    bd = _get_bright_data()
    matches: list[PlagiarismMatch] = []

    for passage in passages:
        try:
            search_query = f'"{passage[:80]}"'
            results = await bd.search(search_query, num=5, engine="google")
            for r in results:
                if r.url != req.url and r.url not in [m.source_url for m in matches]:
                    matches.append(PlagiarismMatch(
                        passage=passage[:200],
                        source_url=r.url,
                        source_title=r.title,
                        similarity="high" if passage[:40].lower() in r.description.lower() else "moderate",
                    ))
        except Exception as e:
            logger.warning("Search failed for passage: %s", e)

    # Step 3: Synthesize verdict
    synth_prompt = f"""You are a plagiarism analysis system. Given the original content and search results, determine the originality.

ORIGINAL URL: {req.url}
CONTENT PREVIEW:
{content[:3000]}

SEARCH MATCHES FOUND: {len(matches)}
{chr(10).join(f'- "{m.passage[:80]}..." found at {m.source_url} ({m.similarity} similarity)' for m in matches[:10])}

Provide your analysis in EXACTLY this format (no markdown fences):
ORIGINALITY: <0.0 to 1.0 where 1.0 is fully original>
VERDICT: <original|partially_plagiarized|heavily_plagiarized>
SUMMARY: <2-3 sentence assessment>

Consider: Are the matches from the same author? Are they common phrases? Is this content clearly copied or just covering the same topic?"""

    try:
        synth_text = await _call_claude(synth_prompt, model="sonnet")

        originality = 0.8
        verdict = "original"
        summary = ""

        for line in synth_text.split("\n"):
            line = line.strip()
            if line.startswith("ORIGINALITY:"):
                try:
                    originality = float(line.split(":", 1)[1].strip())
                    originality = max(0.0, min(1.0, originality))
                except ValueError:
                    pass
            elif line.startswith("VERDICT:"):
                v = line.split(":", 1)[1].strip().lower()
                if v in ("original", "partially_plagiarized", "heavily_plagiarized"):
                    verdict = v
            elif line.startswith("SUMMARY:"):
                summary = line.split(":", 1)[1].strip()

        return PlagiarismResult(
            url=req.url,
            originality_score=originality,
            verdict=verdict,
            summary=summary or "Analysis completed.",
            matches=matches[:10],
            content_preview=preview,
        )
    except Exception as e:
        logger.error("Plagiarism synthesis failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")
