"""Mini-tool endpoints — AI detection and plagiarism checking."""

import asyncio
import os
import re
import tempfile

import httpx
from fastapi import APIRouter, File, HTTPException, UploadFile
from pydantic import BaseModel

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ResultMessage,
    TextBlock,
    query,
)

from engine.agents.base import _get_api_key
from engine.logging_config import get_logger
from engine.tools.bright_data import BrightDataClient, ScrapedPage

logger = get_logger(__name__)

router = APIRouter(prefix="/api/tools", tags=["tools"])

# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    url: str
    mode: str = "text"  # "text" | "image" | "auto"


class DetectionResult(BaseModel):
    url: str
    verdict: str            # "ai_generated" | "human_written" | "mixed" | "inconclusive"
    confidence: float       # 0-1
    summary: str
    indicators: list[str]
    content_type: str       # "text" | "image"
    content_preview: str    # first ~300 chars of scraped content


class ImageAnalyzeRequest(BaseModel):
    url: str


class ImageDetectionResult(BaseModel):
    url: str
    verdict: str            # "ai_generated" | "human_created" | "inconclusive"
    confidence: float       # 0-1
    summary: str
    indicators: list[str]
    image_url: str


class PlagiarismRequest(BaseModel):
    url: str


class PlagiarismMatch(BaseModel):
    passage: str
    source_url: str
    source_title: str
    similarity: str  # "high" | "moderate" | "low"


class PlagiarismResult(BaseModel):
    url: str
    originality_score: float  # 0-1 (1 = fully original)
    verdict: str              # "original" | "partially_plagiarized" | "heavily_plagiarized"
    summary: str
    matches: list[PlagiarismMatch]
    content_preview: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_env() -> dict[str, str]:
    """Build env dict with API key for Claude Agent SDK calls."""
    env: dict[str, str] = {}
    if api_key := _get_api_key():
        env["ANTHROPIC_API_KEY"] = api_key
    return env


async def _call_claude(
    prompt: str,
    model: str = "sonnet",
    tools: list[str] | None = None,
    max_turns: int = 1,
    timeout: int = 120,
) -> str:
    """Call Claude via the Agent SDK (same auth as the research engine)."""
    env = _build_env()
    options = ClaudeAgentOptions(
        model=model,
        max_turns=max_turns,
        allowed_tools=tools or [],
        system_prompt="You are an analysis assistant. Follow instructions precisely and output in the exact format requested.",
        env=env,
    )

    response_text = ""

    async def _run():
        nonlocal response_text
        async for message in query(prompt=prompt, options=options):
            if isinstance(message, AssistantMessage):
                for block in message.content:
                    if isinstance(block, TextBlock):
                        response_text += block.text

    await asyncio.wait_for(_run(), timeout=timeout)
    return response_text


def _get_bright_data() -> BrightDataClient:
    return BrightDataClient()


async def _scrape_url(url: str) -> ScrapedPage:
    """Scrape a URL via Bright Data and return markdown content."""
    bd = _get_bright_data()
    try:
        page = await bd.scrape_page(url, fmt="markdown")
        if page.ok:
            return page
        return ScrapedPage(url=url, content="", ok=False, error=page.error or "Failed to scrape page")
    except Exception as e:
        logger.warning("Scrape failed for %s: %s", url, e)
        return ScrapedPage(url=url, content="", ok=False, error=str(e))


# ---------------------------------------------------------------------------
# AI Content Detection
# ---------------------------------------------------------------------------

@router.post("/detect-ai", response_model=DetectionResult)
async def detect_ai_content(req: AnalyzeRequest):
    """Detect whether content at a URL is AI-generated."""
    page = await _scrape_url(req.url)
    if not page.ok or not page.content.strip():
        raise HTTPException(status_code=422, detail=f"Could not scrape content from URL: {page.error or 'empty page'}")

    content = page.content[:12000]  # cap for context window
    preview = page.content[:300]

    prompt = f"""Analyze the following web content and determine whether it was written by a human or generated by AI (like ChatGPT, Claude, etc.).

URL: {req.url}

CONTENT:
{content}

Provide your analysis in EXACTLY this format (no markdown fences):
VERDICT: <ai_generated|human_written|mixed|inconclusive>
CONFIDENCE: <0.0 to 1.0>
SUMMARY: <2-3 sentence explanation>
INDICATORS:
- <indicator 1>
- <indicator 2>
- <indicator 3>
- <indicator 4>
- <indicator 5>

Focus on: repetitive sentence structures, lack of personal voice, hedging language ("It's important to note"), formulaic transitions, unusual uniformity in paragraph length, lack of specific personal experience, generic examples, and characteristic AI phrasings."""

    try:
        text = await _call_claude(prompt, model="sonnet")

        verdict = "inconclusive"
        confidence = 0.5
        summary = ""
        indicators: list[str] = []

        for line in text.split("\n"):
            line = line.strip()
            if line.startswith("VERDICT:"):
                v = line.split(":", 1)[1].strip().lower()
                if v in ("ai_generated", "human_written", "mixed", "inconclusive"):
                    verdict = v
            elif line.startswith("CONFIDENCE:"):
                try:
                    confidence = float(line.split(":", 1)[1].strip())
                    confidence = max(0.0, min(1.0, confidence))
                except ValueError:
                    pass
            elif line.startswith("SUMMARY:"):
                summary = line.split(":", 1)[1].strip()
            elif line.startswith("- "):
                indicators.append(line[2:].strip())

        return DetectionResult(
            url=req.url,
            verdict=verdict,
            confidence=confidence,
            summary=summary or "Analysis completed.",
            indicators=indicators[:8],
            content_type="text",
            content_preview=preview,
        )
    except Exception as e:
        logger.error("AI detection failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")


# ---------------------------------------------------------------------------
# Plagiarism Checking
# ---------------------------------------------------------------------------

@router.post("/check-plagiarism", response_model=PlagiarismResult)
async def check_plagiarism(req: PlagiarismRequest):
    """Check content at a URL for potential plagiarism."""
    page = await _scrape_url(req.url)
    if not page.ok or not page.content.strip():
        raise HTTPException(status_code=422, detail=f"Could not scrape content from URL: {page.error or 'empty page'}")

    content = page.content[:12000]
    preview = page.content[:300]

    # Step 1: Extract key passages for search
    extract_prompt = f"""Extract 5 distinctive passages (1-2 sentences each) from this content that would be most useful for plagiarism detection. Choose passages with specific claims, unique phrasing, or factual statements — not generic introductions.

CONTENT:
{content}

Return ONLY the passages, one per line, prefixed with PASSAGE: (no numbering, no quotes)."""

    try:
        extract_text = await _call_claude(extract_prompt, model="haiku")
        passages = []
        for line in extract_text.split("\n"):
            line = line.strip()
            if line.startswith("PASSAGE:"):
                p = line.split(":", 1)[1].strip().strip('"').strip("'")
                if len(p) > 20:
                    passages.append(p)
        passages = passages[:5]

        if not passages:
            # Fallback: split content into chunks
            sentences = re.split(r'(?<=[.!?])\s+', content)
            passages = [s for s in sentences if len(s) > 40][:5]

    except Exception as e:
        logger.error("Passage extraction failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")

    # Step 2: Search for each passage
    bd = _get_bright_data()
    matches: list[PlagiarismMatch] = []

    for passage in passages:
        try:
            search_query = f'"{passage[:80]}"'
            results = await bd.search(search_query, num=5, engine="google")
            for r in results:
                if r.url != req.url and r.url not in [m.source_url for m in matches]:
                    matches.append(PlagiarismMatch(
                        passage=passage[:200],
                        source_url=r.url,
                        source_title=r.title,
                        similarity="high" if passage[:40].lower() in r.description.lower() else "moderate",
                    ))
        except Exception as e:
            logger.warning("Search failed for passage: %s", e)

    # Step 3: Synthesize verdict
    synth_prompt = f"""You are a plagiarism analysis system. Given the original content and search results, determine the originality.

ORIGINAL URL: {req.url}
CONTENT PREVIEW:
{content[:3000]}

SEARCH MATCHES FOUND: {len(matches)}
{chr(10).join(f'- "{m.passage[:80]}..." found at {m.source_url} ({m.similarity} similarity)' for m in matches[:10])}

Provide your analysis in EXACTLY this format (no markdown fences):
ORIGINALITY: <0.0 to 1.0 where 1.0 is fully original>
VERDICT: <original|partially_plagiarized|heavily_plagiarized>
SUMMARY: <2-3 sentence assessment>

Consider: Are the matches from the same author? Are they common phrases? Is this content clearly copied or just covering the same topic?"""

    try:
        synth_text = await _call_claude(synth_prompt, model="sonnet")

        originality = 0.8
        verdict = "original"
        summary = ""

        for line in synth_text.split("\n"):
            line = line.strip()
            if line.startswith("ORIGINALITY:"):
                try:
                    originality = float(line.split(":", 1)[1].strip())
                    originality = max(0.0, min(1.0, originality))
                except ValueError:
                    pass
            elif line.startswith("VERDICT:"):
                v = line.split(":", 1)[1].strip().lower()
                if v in ("original", "partially_plagiarized", "heavily_plagiarized"):
                    verdict = v
            elif line.startswith("SUMMARY:"):
                summary = line.split(":", 1)[1].strip()

        return PlagiarismResult(
            url=req.url,
            originality_score=originality,
            verdict=verdict,
            summary=summary or "Analysis completed.",
            matches=matches[:10],
            content_preview=preview,
        )
    except Exception as e:
        logger.error("Plagiarism synthesis failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Analysis failed: {str(e)}")


# ---------------------------------------------------------------------------
# AI Image Detection
# ---------------------------------------------------------------------------

async def _download_image(url: str) -> str:
    """Download image from URL to a temp file. Returns the file path."""
    async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
        resp = await client.get(url, headers={"User-Agent": "Mozilla/5.0"})
        resp.raise_for_status()
        content_type = resp.headers.get("content-type", "")
        if not content_type.startswith("image/"):
            raise ValueError(f"URL is not an image (content-type: {content_type})")

        ext = ".jpg"
        if "png" in content_type:
            ext = ".png"
        elif "webp" in content_type:
            ext = ".webp"
        elif "gif" in content_type:
            ext = ".gif"

        fd, path = tempfile.mkstemp(suffix=ext, prefix="veritas_img_")
        with os.fdopen(fd, "wb") as f:
            f.write(resp.content)
        return path


def _extract_image_metadata(filepath: str) -> dict:
    """Extract rich metadata from an image file for AI detection analysis."""
    from PIL import Image
    from PIL.ExifTags import TAGS

    img = Image.open(filepath)
    file_size = os.path.getsize(filepath)

    meta: dict = {
        "format": img.format or "unknown",
        "width": img.width,
        "height": img.height,
        "mode": img.mode,
        "file_size_kb": round(file_size / 1024, 1),
        "aspect_ratio": round(img.width / max(img.height, 1), 3),
    }

    # Check if dimensions are common AI sizes
    ai_sizes = {256, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1152, 1280, 1344, 1408, 1472, 1536, 2048, 4096}
    meta["width_is_ai_typical"] = img.width in ai_sizes
    meta["height_is_ai_typical"] = img.height in ai_sizes
    meta["both_dims_ai_typical"] = img.width in ai_sizes and img.height in ai_sizes
    meta["is_square"] = img.width == img.height

    # EXIF analysis
    exif = img.getexif()
    meta["has_exif"] = bool(exif)
    meta["exif_tag_count"] = len(exif) if exif else 0

    if exif:
        exif_details = {}
        for tag_id, value in exif.items():
            tag_name = TAGS.get(tag_id, str(tag_id))
            try:
                if isinstance(value, bytes):
                    exif_details[tag_name] = f"<binary {len(value)} bytes>"
                elif isinstance(value, (str, int, float)):
                    exif_details[tag_name] = str(value)[:200]
            except Exception:
                pass
        meta["exif_tags"] = exif_details

        # Key camera fields
        meta["has_camera_make"] = "Make" in exif_details
        meta["has_camera_model"] = "Model" in exif_details
        meta["has_datetime"] = "DateTime" in exif_details or "DateTimeOriginal" in exif_details
        meta["has_gps"] = any("GPS" in k for k in exif_details)
        meta["software"] = exif_details.get("Software", "none")
    else:
        meta["has_camera_make"] = False
        meta["has_camera_model"] = False
        meta["has_datetime"] = False
        meta["has_gps"] = False
        meta["software"] = "none"

    # Color analysis
    try:
        small = img.convert("RGB").resize((64, 64))
        pixels = list(small.getdata())
        r_vals = [p[0] for p in pixels]
        g_vals = [p[1] for p in pixels]
        b_vals = [p[2] for p in pixels]

        def _stats(vals: list[int]) -> dict:
            n = len(vals)
            mean = sum(vals) / n
            variance = sum((v - mean) ** 2 for v in vals) / n
            return {"mean": round(mean, 1), "std": round(variance ** 0.5, 1), "min": min(vals), "max": max(vals)}

        meta["color_r"] = _stats(r_vals)
        meta["color_g"] = _stats(g_vals)
        meta["color_b"] = _stats(b_vals)

        # Unique color count (in 64x64 thumbnail)
        meta["unique_colors_64x64"] = len(set(pixels))

        # Check for unnaturally smooth gradients (low unique colors = synthetic)
        meta["color_diversity_ratio"] = round(len(set(pixels)) / len(pixels), 3)
    except Exception:
        pass

    # PNG-specific: check for tEXt chunks (AI tools embed metadata here)
    if img.format == "PNG" and hasattr(img, "info"):
        png_text = {}
        for k, v in img.info.items():
            if isinstance(v, str) and len(v) < 500:
                png_text[k] = v
            elif isinstance(v, str):
                png_text[k] = v[:200] + "..."
        if png_text:
            meta["png_text_chunks"] = png_text

    img.close()
    return meta


async def _analyze_image_file(filepath: str, source_url: str) -> ImageDetectionResult:
    """Analyze image metadata with Claude to determine if AI-generated."""
    try:
        metadata = _extract_image_metadata(filepath)
    except Exception as e:
        logger.error("Image metadata extraction failed: %s", e)
        raise HTTPException(status_code=422, detail=f"Could not read image: {str(e)}")

    import json
    meta_str = json.dumps(metadata, indent=2, default=str)

    prompt = f"""You are an expert AI-generated image forensic analyst. Analyze this image's metadata and properties to determine if it was generated by AI (DALL-E, Midjourney, Stable Diffusion, Flux, etc.) or is a real photograph / human-created artwork.

SOURCE: {source_url}

IMAGE METADATA:
{meta_str}

Key forensic signals to evaluate:

1. **EXIF Data**: Real camera photos almost always have EXIF with Make, Model, DateTime, lens info. AI images typically have NO EXIF or minimal EXIF. This is the strongest single signal.

2. **Dimensions**: AI generators commonly output power-of-2 or standard sizes (512x512, 768x1024, 1024x1024, 1344x768, etc.). Real photos have irregular camera-sensor sizes (4032x3024, 6000x4000, etc.).

3. **Software Field**: Check for AI tool names in software/generator fields (e.g., "DALL-E", "Midjourney", "Stable Diffusion", "ComfyUI", "NovelAI", "Adobe Firefly").

4. **PNG Text Chunks**: AI tools (especially Stable Diffusion/ComfyUI) embed generation parameters in PNG text chunks (look for "parameters", "prompt", "workflow", "sampler", "cfg_scale", "steps", "seed").

5. **Color Properties**: AI images often have smoother color distributions, lower color diversity, and specific noise patterns.

6. **Aspect Ratio**: Exact square (1:1) or common AI ratios (4:3, 3:2 at exact power-of-2 dims) are more suspicious.

7. **File Size**: AI images often have specific compression patterns.

Weigh these signals together. EXIF absence + AI-typical dimensions is very strong evidence. Full camera EXIF with sensor data is very strong counter-evidence.

Provide your analysis in EXACTLY this format (no markdown fences):
VERDICT: <ai_generated|human_created|inconclusive>
CONFIDENCE: <0.0 to 1.0>
SUMMARY: <2-3 sentence explanation>
INDICATORS:
- <specific finding 1>
- <specific finding 2>
- <specific finding 3>
- <specific finding 4>
- <specific finding 5>"""

    text = await _call_claude(prompt, model="sonnet")

    verdict = "inconclusive"
    confidence = 0.5
    summary = ""
    indicators: list[str] = []

    for line in text.split("\n"):
        line = line.strip()
        if line.startswith("VERDICT:"):
            v = line.split(":", 1)[1].strip().lower()
            if v in ("ai_generated", "human_created", "inconclusive"):
                verdict = v
        elif line.startswith("CONFIDENCE:"):
            try:
                confidence = float(line.split(":", 1)[1].strip())
                confidence = max(0.0, min(1.0, confidence))
            except ValueError:
                pass
        elif line.startswith("SUMMARY:"):
            summary = line.split(":", 1)[1].strip()
        elif line.startswith("- "):
            indicators.append(line[2:].strip())

    return ImageDetectionResult(
        url=source_url,
        verdict=verdict,
        confidence=confidence,
        summary=summary or "Analysis completed.",
        indicators=indicators[:8],
        image_url=source_url,
    )


@router.post("/detect-ai-image", response_model=ImageDetectionResult)
async def detect_ai_image(req: ImageAnalyzeRequest):
    """Detect whether an image at a URL is AI-generated."""
    try:
        filepath = await _download_image(req.url)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=422, detail=f"Could not download image: {str(e)}")

    try:
        return await _analyze_image_file(filepath, req.url)
    except Exception as e:
        logger.error("AI image detection failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Image analysis failed: {str(e)}")
    finally:
        try:
            os.unlink(filepath)
        except OSError:
            pass


@router.post("/detect-ai-image-upload", response_model=ImageDetectionResult)
async def detect_ai_image_upload(file: UploadFile = File(...)):
    """Detect whether an uploaded image is AI-generated."""
    content_type = file.content_type or ""
    if not content_type.startswith("image/"):
        raise HTTPException(status_code=422, detail=f"File is not an image (type: {content_type})")

    ext = ".jpg"
    if "png" in content_type:
        ext = ".png"
    elif "webp" in content_type:
        ext = ".webp"
    elif "gif" in content_type:
        ext = ".gif"

    fd, filepath = tempfile.mkstemp(suffix=ext, prefix="veritas_img_")
    try:
        data = await file.read()
        with os.fdopen(fd, "wb") as f:
            f.write(data)

        return await _analyze_image_file(filepath, f"upload://{file.filename or 'image'}")
    except HTTPException:
        raise
    except Exception as e:
        logger.error("AI image upload detection failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Image analysis failed: {str(e)}")
    finally:
        try:
            os.unlink(filepath)
        except OSError:
            pass
